//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.qian.activity;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import com.qian.workeveryday.R.id;
import com.qian.workeveryday.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class AddDayJobDetail_
    extends AddDayJobDetail
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String WORK_INFO_ID_EXTRA = "workInfoID";
    public final static String WORK_END_DATE_EXTRA = "endDate";
    public final static String WORK_START_DATE_EXTRA = "startDate";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.add_day_job_detail);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static AddDayJobDetail_.IntentBuilder_ intent(Context context) {
        return new AddDayJobDetail_.IntentBuilder_(context);
    }

    public static AddDayJobDetail_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new AddDayJobDetail_.IntentBuilder_(fragment);
    }

    public static AddDayJobDetail_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new AddDayJobDetail_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        mInput = ((EditText) hasViews.findViewById(id.ed_addDayJobDetail_jobContent));
        mDate = ((EditText) hasViews.findViewById(id.tv_addDayJobDetail_showTime));
        {
            View view = hasViews.findViewById(id.btn_addDayJobDetail_reset);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        AddDayJobDetail_.this.clickListener(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.btn_addDayJobDetail_sub);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        AddDayJobDetail_.this.clickListener(view);
                    }

                }
                );
            }
        }
        initData();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(WORK_INFO_ID_EXTRA)) {
                workInfoID = extras_.getInt(WORK_INFO_ID_EXTRA);
            }
            if (extras_.containsKey(WORK_END_DATE_EXTRA)) {
                workEndDate = extras_.getString(WORK_END_DATE_EXTRA);
            }
            if (extras_.containsKey(WORK_START_DATE_EXTRA)) {
                workStartDate = extras_.getString(WORK_START_DATE_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<AddDayJobDetail_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, AddDayJobDetail_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), AddDayJobDetail_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), AddDayJobDetail_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

        public AddDayJobDetail_.IntentBuilder_ workInfoID(int workInfoID) {
            return super.extra(WORK_INFO_ID_EXTRA, workInfoID);
        }

        public AddDayJobDetail_.IntentBuilder_ workEndDate(String workEndDate) {
            return super.extra(WORK_END_DATE_EXTRA, workEndDate);
        }

        public AddDayJobDetail_.IntentBuilder_ workStartDate(String workStartDate) {
            return super.extra(WORK_START_DATE_EXTRA, workStartDate);
        }

    }

}
