//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.qian.activity;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import com.qian.workeveryday.R.id;
import com.qian.workeveryday.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class AddOtherCostActivity_
    extends AddOtherCostActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String WORK_INFO_ID_EXTRA = "workInfoID";
    public final static String DATE_EXTRA = "date";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.add_other_cost);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static AddOtherCostActivity_.IntentBuilder_ intent(Context context) {
        return new AddOtherCostActivity_.IntentBuilder_(context);
    }

    public static AddOtherCostActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new AddOtherCostActivity_.IntentBuilder_(fragment);
    }

    public static AddOtherCostActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new AddOtherCostActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        mMoney = ((EditText) hasViews.findViewById(id.ed_addOtherCost_money));
        mContent = ((EditText) hasViews.findViewById(id.ed_addOtherCost_content));
        {
            View view = hasViews.findViewById(id.btn_addOtherCost_reset);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        AddOtherCostActivity_.this.clickListener(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.btn_addOtherCost_ok);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        AddOtherCostActivity_.this.clickListener(view);
                    }

                }
                );
            }
        }
        initData();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(WORK_INFO_ID_EXTRA)) {
                workInfoID = extras_.getInt(WORK_INFO_ID_EXTRA);
            }
            if (extras_.containsKey(DATE_EXTRA)) {
                date = extras_.getString(DATE_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<AddOtherCostActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, AddOtherCostActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), AddOtherCostActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), AddOtherCostActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

        public AddOtherCostActivity_.IntentBuilder_ workInfoID(int workInfoID) {
            return super.extra(WORK_INFO_ID_EXTRA, workInfoID);
        }

        public AddOtherCostActivity_.IntentBuilder_ date(String date) {
            return super.extra(DATE_EXTRA, date);
        }

    }

}
