//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.qian.activity;

import android.content.Context;
import android.content.Intent;
import android.content.res.Resources;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.TextView;
import com.qian.workeveryday.R.array;
import com.qian.workeveryday.R.id;
import com.qian.workeveryday.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class AddTransportDetail_
    extends AddTransportDetail
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String DATE_EXTRA = "date";
    public final static String JOB_ID_EXTRA = "jobID";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.add_trans);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        Resources resources_ = this.getResources();
        mTypeValues = resources_.getStringArray(array.transportationType);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static AddTransportDetail_.IntentBuilder_ intent(Context context) {
        return new AddTransportDetail_.IntentBuilder_(context);
    }

    public static AddTransportDetail_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new AddTransportDetail_.IntentBuilder_(fragment);
    }

    public static AddTransportDetail_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new AddTransportDetail_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        mTime = ((EditText) hasViews.findViewById(id.ed_addTrans_time));
        mCost = ((EditText) hasViews.findViewById(id.ed_addTrans_cost));
        mDate = ((TextView) hasViews.findViewById(id.tv_addTrans_showDate));
        mSpinner = ((Spinner) hasViews.findViewById(id.spinner_addTrans_type));
        {
            View view = hasViews.findViewById(id.btn_addTrans_ok);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        AddTransportDetail_.this.clickListener();
                    }

                }
                );
            }
        }
        initData();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(DATE_EXTRA)) {
                date = extras_.getString(DATE_EXTRA);
            }
            if (extras_.containsKey(JOB_ID_EXTRA)) {
                jobID = extras_.getInt(JOB_ID_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<AddTransportDetail_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, AddTransportDetail_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), AddTransportDetail_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), AddTransportDetail_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

        public AddTransportDetail_.IntentBuilder_ date(String date) {
            return super.extra(DATE_EXTRA, date);
        }

        public AddTransportDetail_.IntentBuilder_ jobID(int jobID) {
            return super.extra(JOB_ID_EXTRA, jobID);
        }

    }

}
